// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ClearDataResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success',
            description: 'Whether operation succeeded'
        },
        message: {
            type: 'string',
            title: 'Message',
            description: 'Result message'
        },
        cleared_size_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cleared Size Mb',
            description: 'Size of cleared data in MB'
        }
    },
    type: 'object',
    required: ['success', 'message'],
    title: 'ClearDataResponse',
    description: `Response model for data clearing operation.

Educational Notes:
- Simple response to confirm operation`
} as const;

export const DataHandlerConfigSchema = {
    properties: {
        class_name: {
            type: 'string',
            title: 'Class Name',
            description: "Class name of the Qlib component (e.g., 'LGBModel', 'Alpha158')"
        },
        module_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Module Path',
            description: "Python module path where the class is located (e.g., 'qlib.contrib.model.gbdt'). If not provided, will be automatically filled by backend based on class_name."
        },
        kwargs: {
            additionalProperties: true,
            type: 'object',
            title: 'Kwargs',
            description: "Keyword arguments passed to the component's __init__ method"
        }
    },
    type: 'object',
    required: ['class_name'],
    title: 'DataHandlerConfig',
    description: `Configuration for Qlib Data Handler (e.g., Alpha158)

Educational Notes:
- Data Handler processes raw data into features for model training
- Alpha158 is Qlib's built-in 158 alpha factors
- Inherits class_name, module_path, kwargs from QlibComponentConfig
- Handler kwargs include time ranges and instrument selection`
} as const;

export const DataSourceStatusSchema = {
    properties: {
        source_name: {
            type: 'string',
            title: 'Source Name',
            description: 'Current data source name'
        },
        data_exists: {
            type: 'boolean',
            title: 'Data Exists',
            description: 'Whether data exists in qlib_data directory'
        },
        data_range_start: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Range Start',
            description: 'Start date of available data'
        },
        data_range_end: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Range End',
            description: 'End date of available data'
        },
        instruments: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instruments',
            description: 'List of stock codes (first 10 if more than 10)'
        },
        instruments_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instruments Count',
            description: 'Number of stocks'
        },
        stock_pool: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock Pool',
            description: "Stock pool name (e.g., 'csi300', 'csi500', 'all')"
        },
        features: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Features',
            description: "List of available features (e.g., ['open', 'close', 'high', 'low', 'volume'])"
        },
        data_size_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Size Mb',
            description: 'Total data size in MB'
        },
        last_updated: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Updated',
            description: 'Last update timestamp'
        }
    },
    type: 'object',
    required: ['source_name', 'data_exists'],
    title: 'DataSourceStatus',
    description: `Data source status information.

Educational Notes:
- This model represents the current state of the data
- Used to display information to users
- Not stored in database, just for API response`
} as const;

export const DatasetConfigSchema = {
    properties: {
        class_name: {
            type: 'string',
            title: 'Class Name',
            description: "Dataset class name (e.g., 'DatasetH')"
        },
        module_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Module Path',
            description: "Module path for dataset (e.g., 'qlib.data.dataset'). If not provided, will be automatically filled by backend based on class_name."
        },
        kwargs: {
            '$ref': '#/components/schemas/DatasetKwargs',
            description: 'Dataset configuration including handler and segments'
        }
    },
    type: 'object',
    required: ['class_name', 'kwargs'],
    title: 'DatasetConfig',
    description: `Configuration for Qlib Dataset (e.g., DatasetH).

Educational Notes:
- Dataset handles data preprocessing and train/valid/test splitting
- DatasetH is Qlib's hierarchical dataset for time series data
# Contains handler config and segment definitions`
} as const;

export const DatasetKwargsSchema = {
    properties: {
        handler: {
            '$ref': '#/components/schemas/DataHandlerConfig',
            description: 'Data handler configuration for feature processing'
        },
        segments: {
            '$ref': '#/components/schemas/DatasetSegments',
            description: 'Time-based data segments for train/valid/test splits'
        }
    },
    type: 'object',
    required: ['handler', 'segments'],
    title: 'DatasetKwargs',
    description: `Dataset kwargs containing handler and segments.

Educational Notes:
- Dataset kwargs combine data processing (handler) and time splitting (segments)
- Handler defines how raw data becomes features
- Segments define how data is split for training/validation/testing`
} as const;

export const DatasetSegmentsSchema = {
    properties: {
        train: {
            prefixItems: [
                {
                    type: 'string'
                },
                {
                    type: 'string'
                }
            ],
            type: 'array',
            maxItems: 2,
            minItems: 2,
            title: 'Train',
            description: 'Training period as (start_date, end_date) tuple'
        },
        valid: {
            prefixItems: [
                {
                    type: 'string'
                },
                {
                    type: 'string'
                }
            ],
            type: 'array',
            maxItems: 2,
            minItems: 2,
            title: 'Valid',
            description: 'Validation period as (start_date, end_date) tuple'
        },
        test: {
            prefixItems: [
                {
                    type: 'string'
                },
                {
                    type: 'string'
                }
            ],
            type: 'array',
            maxItems: 2,
            minItems: 2,
            title: 'Test',
            description: 'Test period as (start_date, end_date) tuple'
        }
    },
    type: 'object',
    required: ['train', 'valid', 'test'],
    title: 'DatasetSegments',
    description: `Time-based segments for train/validation/test splits.

Educational Notes:
- Qlib uses time-based splitting for financial data
- Each segment is a tuple of (start_date, end_date)
- Ensures no look-ahead bias in model training`
} as const;

export const DownloadDataRequestSchema = {
    properties: {
        stock_pool: {
            type: 'string',
            title: 'Stock Pool',
            description: "Stock pool to download (e.g., 'csi300', 'csi500')",
            default: 'csi300'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date in YYYY-MM-DD format'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date in YYYY-MM-DD format'
        },
        incremental: {
            type: 'boolean',
            title: 'Incremental',
            description: 'Whether to perform incremental update (append new data only)',
            default: false
        },
        interval: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interval',
            description: "Data interval: '1d' for daily data, '1m' for minute data",
            default: '1d'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date'],
    title: 'DownloadDataRequest',
    description: `Request model for downloading data.

Educational Notes:
- This defines what parameters users need to provide
- Validation is automatic through Pydantic
- Data source is now controlled by configuration, not user input`
} as const;

export const DownloadTaskResponseSchema = {
    properties: {
        task_id: {
            type: 'string',
            title: 'Task Id',
            description: 'Unique task identifier'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: "Initial status: 'started'"
        },
        message: {
            type: 'string',
            title: 'Message',
            description: 'Human-readable message'
        }
    },
    type: 'object',
    required: ['task_id', 'status', 'message'],
    title: 'DownloadTaskResponse',
    description: `Response model for download task creation.

Educational Notes:
- Returned immediately when user starts download
- Contains task_id for tracking progress`
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModelConfigSchema = {
    properties: {
        class_name: {
            type: 'string',
            title: 'Class Name',
            description: "Class name of the Qlib component (e.g., 'LGBModel', 'Alpha158')"
        },
        module_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Module Path',
            description: "Python module path where the class is located (e.g., 'qlib.contrib.model.gbdt'). If not provided, will be automatically filled by backend based on class_name."
        },
        kwargs: {
            additionalProperties: true,
            type: 'object',
            title: 'Kwargs',
            description: "Keyword arguments passed to the component's __init__ method"
        }
    },
    type: 'object',
    required: ['class_name'],
    title: 'ModelConfig',
    description: `Configuration for Qlib Model (e.g., LGBModel).

Educational Notes:
- Model defines the machine learning algorithm for prediction
- LGBModel is LightGBM implementation optimized for financial data
- Model kwargs include hyperparameters like learning_rate, num_leaves
- Inherits all fields from QlibComponentConfig (class, module_path, kwargs)`
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TaskConfigSchema = {
    properties: {
        model: {
            '$ref': '#/components/schemas/ModelConfig',
            description: 'Model configuration for training'
        },
        dataset: {
            '$ref': '#/components/schemas/DatasetConfig',
            description: 'Dataset configuration for data processing'
        }
    },
    type: 'object',
    required: ['model', 'dataset'],
    title: 'TaskConfig',
    description: `Qlib Task configuration containing model and dataset.

Educational Notes:
- Task is the core unit of execution in Qlib workflows
- Combines model, dataset, and optional record configurations
- Maps directly to Qlib's task section in YAML configs`
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrainingWorkflowRequestSchema = {
    properties: {
        experiment_name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Experiment Name',
            description: 'Name for the training experiment (used in MLflow tracking)',
            default: 'default_experiment'
        },
        task: {
            '$ref': '#/components/schemas/TaskConfig',
            description: 'Task configuration containing model and dataset settings'
        }
    },
    type: 'object',
    required: ['task'],
    title: 'TrainingWorkflowRequest',
    description: `Request model for training workflow API.

Educational Notes:
- Follows Qlib's workflow configuration structure exactly
# Allows users to specify complete training pipeline
- Experiment name helps organize and track different runs`
} as const;

export const TrainingWorkflowResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            description: "Execution status ('success' or 'error')"
        },
        predictions_count: {
            type: 'integer',
            title: 'Predictions Count',
            description: 'Number of predictions generated on test set'
        },
        model_saved: {
            type: 'boolean',
            title: 'Model Saved',
            description: 'Whether the trained model was successfully saved'
        },
        experiment_name: {
            type: 'string',
            title: 'Experiment Name',
            description: 'Name of the experiment that was executed'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message',
            description: "Error message if status is 'error'"
        }
    },
    type: 'object',
    required: ['status', 'predictions_count', 'model_saved', 'experiment_name'],
    title: 'TrainingWorkflowResponse',
    description: `Response model for training workflow API.

Educational Notes:
- Provides comprehensive feedback on training execution
- Predictions count indicates model's output on test set
- Model saved status confirms persistence for future use`
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;