// This file is auto-generated by @hey-api/openapi-ts

export const BacktestRequestSchema = {
    properties: {
        benchmark: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Benchmark',
            description: 'Benchmark symbol for comparison (default: SH000300)',
            example: 'SH000300'
        },
        topk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topk',
            description: 'Number of stocks to hold (default: 50)',
            example: 50
        },
        n_drop: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'N Drop',
            description: 'Number of stocks to drop each day (default: 5)',
            example: 5
        },
        account: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account',
            description: 'Initial account value (default: 100000000)',
            example: 100000000
        }
    },
    type: 'object',
    title: 'BacktestRequest',
    description: 'Request model for backtest endpoint.'
} as const;

export const BacktestResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        freq: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Freq'
        },
        trading_days: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Days'
        },
        signal_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Signal Count'
        },
        total_return: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Return'
        },
        total_cost: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Cost'
        },
        net_return: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Return'
        },
        final_account: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Account'
        },
        topk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topk'
        },
        n_drop: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'N Drop'
        },
        benchmark: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Benchmark'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'BacktestResponse',
    description: 'Response model for backtest endpoint.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BuyOrderSchema = {
    properties: {
        instrument: {
            type: 'string',
            title: 'Instrument'
        },
        direction: {
            type: 'string',
            title: 'Direction',
            default: 'BUY'
        },
        target_weight: {
            type: 'number',
            title: 'Target Weight'
        },
        reference_price: {
            type: 'number',
            title: 'Reference Price'
        },
        limit_price: {
            type: 'number',
            title: 'Limit Price'
        },
        score: {
            type: 'number',
            title: 'Score'
        },
        instruction: {
            type: 'string',
            title: 'Instruction'
        },
        score_rank: {
            type: 'integer',
            title: 'Score Rank'
        }
    },
    type: 'object',
    required: ['instrument', 'target_weight', 'reference_price', 'limit_price', 'score', 'instruction', 'score_rank'],
    title: 'BuyOrder',
    description: 'Buy order in trading plan.'
} as const;

export const ChartDataResponseSchema = {
    properties: {
        chart_type: {
            type: 'string',
            title: 'Chart Type',
            description: 'Type of chart data'
        },
        data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                }
            ],
            title: 'Data',
            description: 'Chart data - can be dict or list of dicts'
        }
    },
    type: 'object',
    required: ['chart_type', 'data'],
    title: 'ChartDataResponse',
    description: `Chart data response for various chart types.

Educational Notes:
- Different chart types return different data structures
- All time series data uses string dates for JSON compatibility`
} as const;

export const ClearDataResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success',
            description: 'Whether operation succeeded'
        },
        message: {
            type: 'string',
            title: 'Message',
            description: 'Result message'
        },
        cleared_size_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cleared Size Mb',
            description: 'Size of cleared data in MB'
        }
    },
    type: 'object',
    required: ['success', 'message'],
    title: 'ClearDataResponse',
    description: `Response model for data clearing operation.

Educational Notes:
- Simple response to confirm operation`
} as const;

export const ComputationStatusSchema = {
    type: 'string',
    enum: ['pending', 'computing', 'completed', 'failed'],
    title: 'ComputationStatus',
    description: 'Enumeration of factor computation status'
} as const;

export const DataAnomalySchema = {
    properties: {
        instrument: {
            type: 'string',
            title: 'Instrument',
            description: 'Instrument code'
        },
        column: {
            type: 'string',
            title: 'Column',
            description: "Column with anomaly (e.g., 'close', 'volume')"
        },
        date: {
            type: 'string',
            title: 'Date',
            description: 'Date of anomaly occurrence'
        },
        pct_change: {
            type: 'number',
            title: 'Pct Change',
            description: 'Percentage change detected'
        }
    },
    type: 'object',
    required: ['instrument', 'column', 'date', 'pct_change'],
    title: 'DataAnomaly',
    description: 'Details of a detected data anomaly (large step change).'
} as const;

export const DataHealthMetricsSchema = {
    properties: {
        data_exists: {
            type: 'boolean',
            title: 'Data Exists',
            description: 'Whether data exists in qlib_data directory'
        },
        completeness_percentage: {
            type: 'number',
            title: 'Completeness Percentage',
            description: 'Percentage of complete data (0-100)'
        },
        missing_data_count: {
            type: 'integer',
            title: 'Missing Data Count',
            description: 'Number of instruments with missing data'
        },
        missing_data_details: {
            items: {
                '$ref': '#/components/schemas/MissingDataDetail'
            },
            type: 'array',
            title: 'Missing Data Details',
            description: 'Detailed list of missing data by instrument'
        },
        anomaly_count: {
            type: 'integer',
            title: 'Anomaly Count',
            description: 'Number of detected anomalies'
        },
        anomalies: {
            items: {
                '$ref': '#/components/schemas/DataAnomaly'
            },
            type: 'array',
            title: 'Anomalies',
            description: 'Detailed list of anomalies detected'
        },
        integrity_checks: {
            '$ref': '#/components/schemas/IntegrityChecks',
            description: 'Results of integrity checks'
        },
        checked_at: {
            type: 'string',
            title: 'Checked At',
            description: 'Timestamp when check was performed'
        }
    },
    type: 'object',
    required: ['data_exists', 'completeness_percentage', 'missing_data_count', 'missing_data_details', 'anomaly_count', 'anomalies', 'integrity_checks', 'checked_at'],
    title: 'DataHealthMetrics',
    description: `Comprehensive data health metrics.

Educational Notes:
- Provides overview of data quality
- Includes both summary statistics and detailed lists
- Used for monitoring and alerting`
} as const;

export const DataSourceStatusSchema = {
    properties: {
        source_name: {
            type: 'string',
            title: 'Source Name',
            description: 'Current data source name'
        },
        data_exists: {
            type: 'boolean',
            title: 'Data Exists',
            description: 'Whether data exists in qlib_data directory'
        },
        data_range_start: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Range Start',
            description: 'Start date of available data'
        },
        data_range_end: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Range End',
            description: 'End date of available data'
        },
        instruments: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instruments',
            description: 'List of stock codes (first 10 if more than 10)'
        },
        instruments_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instruments Count',
            description: 'Number of stocks'
        },
        stock_pool: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock Pool',
            description: "Stock pool name (e.g., 'csi300', 'csi500', 'all')"
        },
        features: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Features',
            description: "List of available features (e.g., ['open', 'close', 'high', 'low', 'volume'])"
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label',
            description: "Active label name for prediction target (e.g., 'return_1d')"
        },
        data_size_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Size Mb',
            description: 'Total data size in MB'
        },
        last_updated: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Updated',
            description: 'Last update timestamp'
        }
    },
    type: 'object',
    required: ['source_name', 'data_exists'],
    title: 'DataSourceStatus',
    description: `Data source status information.

Educational Notes:
- This model represents the current state of the data
- Used to display information to users
- Not stored in database, just for API response`
} as const;

export const DataStatusResponseSchema = {
    properties: {
        exists: {
            type: 'boolean',
            title: 'Exists'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details'
        }
    },
    type: 'object',
    required: ['exists', 'message', 'details'],
    title: 'DataStatusResponse',
    description: 'Response model for data status check.'
} as const;

export const DownloadDataRequestSchema = {
    properties: {
        stock_pool: {
            type: 'string',
            title: 'Stock Pool',
            description: "Stock pool to download (e.g., 'csi300', 'csi500')",
            default: 'csi300'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date in YYYY-MM-DD format'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date in YYYY-MM-DD format'
        },
        incremental: {
            type: 'boolean',
            title: 'Incremental',
            description: 'Whether to perform incremental update (append new data only)',
            default: false
        },
        interval: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interval',
            description: "Data interval: '1d' for daily data, '1m' for minute data",
            default: '1d'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date'],
    title: 'DownloadDataRequest',
    description: `Request model for downloading data.

Educational Notes:
- This defines what parameters users need to provide
- Validation is automatic through Pydantic
- Data source is now controlled by configuration, not user input`
} as const;

export const DownloadTaskResponseSchema = {
    properties: {
        task_id: {
            type: 'string',
            title: 'Task Id',
            description: 'Unique task identifier'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: "Initial status: 'started'"
        },
        message: {
            type: 'string',
            title: 'Message',
            description: 'Human-readable message'
        }
    },
    type: 'object',
    required: ['task_id', 'status', 'message'],
    title: 'DownloadTaskResponse',
    description: `Response model for download task creation.

Educational Notes:
- Returned immediately when user starts download
- Contains task_id for tracking progress`
} as const;

export const ExecuteRequestSchema = {
    properties: {
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date',
            description: 'Date in YYYY-MM-DD format (None for latest)',
            example: '2026-02-13'
        },
        topk: {
            type: 'integer',
            maximum: 500,
            minimum: 1,
            title: 'Topk',
            description: 'Number of stocks to hold',
            default: 50
        },
        n_drop: {
            type: 'integer',
            maximum: 50,
            minimum: 0,
            title: 'N Drop',
            description: 'Number of stocks to drop each day',
            default: 5
        },
        slippage: {
            type: 'number',
            maximum: 0.1,
            minimum: 0,
            title: 'Slippage',
            description: 'Slippage for price simulation (default 0.1%)',
            default: 0.001
        },
        dry_run: {
            type: 'boolean',
            title: 'Dry Run',
            description: 'If True, simulate without saving',
            default: false
        }
    },
    type: 'object',
    title: 'ExecuteRequest',
    description: 'Request model for execute endpoint.'
} as const;

export const ExecuteResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        dry_run: {
            type: 'boolean',
            title: 'Dry Run',
            default: false
        },
        slippage: {
            type: 'number',
            title: 'Slippage',
            default: 0.001
        },
        sells_executed: {
            type: 'integer',
            title: 'Sells Executed',
            default: 0
        },
        buys_executed: {
            type: 'integer',
            title: 'Buys Executed',
            default: 0
        },
        executed_sells: {
            items: {
                '$ref': '#/components/schemas/TradeItem'
            },
            type: 'array',
            title: 'Executed Sells',
            default: []
        },
        executed_buys: {
            items: {
                '$ref': '#/components/schemas/TradeItem'
            },
            type: 'array',
            title: 'Executed Buys',
            default: []
        },
        final_cash: {
            type: 'number',
            title: 'Final Cash',
            default: 0
        },
        final_position_count: {
            type: 'integer',
            title: 'Final Position Count',
            default: 0
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'ExecuteResponse',
    description: 'Response model for execute endpoint.'
} as const;

export const FactorSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name',
            description: 'Factor name'
        },
        expression: {
            type: 'string',
            title: 'Expression',
            description: 'Factor expression in Qlib format'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Factor description'
        },
        factor_type: {
            '$ref': '#/components/schemas/FactorType',
            description: 'Factor type: feature (X) or label (Y)',
            default: 'feature'
        },
        status: {
            '$ref': '#/components/schemas/FactorStatus',
            description: 'Factor status',
            default: 'active'
        },
        last_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Value',
            description: 'Latest IC value'
        },
        last_ic_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Date',
            description: 'Latest IC calculation date'
        },
        avg_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Ic Value',
            description: 'Average IC value'
        },
        ic_ir_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ic Ir Ratio',
            description: 'IC Information Ratio'
        },
        last_computed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Computed At',
            description: 'Last computation time'
        },
        computation_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ComputationStatus'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Factor computation status'
        },
        data_points_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Points Count',
            description: 'Number of data points computed'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        }
    },
    type: 'object',
    required: ['name', 'expression', 'created_by'],
    title: 'Factor'
} as const;

export const FactorCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name',
            description: 'Factor name'
        },
        expression: {
            type: 'string',
            title: 'Expression',
            description: 'Factor expression in Qlib format'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Factor description'
        },
        factor_type: {
            '$ref': '#/components/schemas/FactorType',
            description: 'Factor type: feature (X) or label (Y)',
            default: 'feature'
        },
        status: {
            '$ref': '#/components/schemas/FactorStatus',
            description: 'Factor status',
            default: 'active'
        },
        last_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Value',
            description: 'Latest IC value'
        },
        last_ic_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Date',
            description: 'Latest IC calculation date'
        },
        avg_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Ic Value',
            description: 'Average IC value'
        },
        ic_ir_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ic Ir Ratio',
            description: 'IC Information Ratio'
        },
        last_computed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Computed At',
            description: 'Last computation time'
        },
        computation_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ComputationStatus'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Factor computation status'
        },
        data_points_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Points Count',
            description: 'Number of data points computed'
        }
    },
    type: 'object',
    required: ['name', 'expression'],
    title: 'FactorCreate'
} as const;

export const FactorStatusSchema = {
    type: 'string',
    enum: ['active', 'inactive'],
    title: 'FactorStatus',
    description: 'Enumeration of factor status'
} as const;

export const FactorTypeSchema = {
    type: 'string',
    enum: ['feature', 'label'],
    title: 'FactorType',
    description: 'Enumeration of factor types - distinguishes features from labels'
} as const;

export const FactorUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        expression: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expression'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        factor_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FactorType'
                },
                {
                    type: 'null'
                }
            ]
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FactorStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'FactorUpdate'
} as const;

export const FeatureImportanceItemSchema = {
    properties: {
        feature: {
            type: 'string',
            title: 'Feature',
            description: 'Feature name'
        },
        importance: {
            type: 'number',
            title: 'Importance',
            description: 'Importance value'
        }
    },
    type: 'object',
    required: ['feature', 'importance'],
    title: 'FeatureImportanceItem',
    description: 'Single feature importance item.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HoldOrderSchema = {
    properties: {
        instrument: {
            type: 'string',
            title: 'Instrument'
        },
        direction: {
            type: 'string',
            title: 'Direction',
            default: 'HOLD'
        },
        current_weight: {
            type: 'number',
            title: 'Current Weight'
        },
        target_weight: {
            type: 'number',
            title: 'Target Weight'
        },
        score: {
            type: 'number',
            title: 'Score'
        },
        score_rank: {
            type: 'integer',
            title: 'Score Rank'
        }
    },
    type: 'object',
    required: ['instrument', 'current_weight', 'target_weight', 'score', 'score_rank'],
    title: 'HoldOrder',
    description: 'Hold order in trading plan.'
} as const;

export const ICMetricsSchema = {
    properties: {
        ic_mean: {
            type: 'number',
            title: 'Ic Mean',
            description: 'Mean IC (Pearson correlation)'
        },
        ic_std: {
            type: 'number',
            title: 'Ic Std',
            description: 'Standard deviation of IC'
        },
        icir: {
            type: 'number',
            title: 'Icir',
            description: 'IC Information Ratio (IC Mean / IC Std)'
        },
        rank_ic_mean: {
            type: 'number',
            title: 'Rank Ic Mean',
            description: 'Mean Rank IC (Spearman correlation)'
        },
        rank_ic_std: {
            type: 'number',
            title: 'Rank Ic Std',
            description: 'Standard deviation of Rank IC'
        },
        rank_icir: {
            type: 'number',
            title: 'Rank Icir',
            description: 'Rank IC Information Ratio'
        }
    },
    type: 'object',
    required: ['ic_mean', 'ic_std', 'icir', 'rank_ic_mean', 'rank_ic_std', 'rank_icir'],
    title: 'ICMetrics',
    description: `IC (Information Coefficient) metrics.

Educational Notes:
- IC measures correlation between predictions and actual returns
- Higher IC indicates better predictive power
- ICIR measures stability of IC (IC Mean / IC Std)`
} as const;

export const IntegrityChecksSchema = {
    properties: {
        required_columns: {
            type: 'boolean',
            title: 'Required Columns',
            description: 'Whether all required OHLCV columns exist'
        },
        factor_column: {
            type: 'boolean',
            title: 'Factor Column',
            description: 'Whether factor column exists and has data'
        },
        directory_case: {
            type: 'boolean',
            title: 'Directory Case',
            description: 'Whether all feature directories are lowercase'
        }
    },
    type: 'object',
    required: ['required_columns', 'factor_column', 'directory_case'],
    title: 'IntegrityChecks',
    description: 'Results of data integrity checks.'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LongShortMetricsSchema = {
    properties: {
        long_short_ann_return: {
            type: 'number',
            title: 'Long Short Ann Return',
            description: 'Annualized long-short return'
        },
        long_short_ann_sharpe: {
            type: 'number',
            title: 'Long Short Ann Sharpe',
            description: 'Annualized long-short Sharpe ratio'
        },
        long_avg_ann_return: {
            type: 'number',
            title: 'Long Avg Ann Return',
            description: 'Annualized long-average return'
        },
        long_avg_ann_sharpe: {
            type: 'number',
            title: 'Long Avg Ann Sharpe',
            description: 'Annualized long-average Sharpe ratio'
        }
    },
    type: 'object',
    required: ['long_short_ann_return', 'long_short_ann_sharpe', 'long_avg_ann_return', 'long_avg_ann_sharpe'],
    title: 'LongShortMetrics',
    description: `Long-Short strategy performance metrics.

Educational Notes:
- Long-Short: Long top 20% stocks, short bottom 20% stocks
- Sharpe Ratio: Return per unit of risk (higher is better)
- Annualized metrics scaled to yearly performance`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MissingDataDetailSchema = {
    properties: {
        instrument: {
            type: 'string',
            title: 'Instrument',
            description: 'Instrument code'
        },
        open: {
            type: 'integer',
            title: 'Open',
            description: 'Number of missing values in open column'
        },
        high: {
            type: 'integer',
            title: 'High',
            description: 'Number of missing values in high column'
        },
        low: {
            type: 'integer',
            title: 'Low',
            description: 'Number of missing values in low column'
        },
        close: {
            type: 'integer',
            title: 'Close',
            description: 'Number of missing values in close column'
        },
        volume: {
            type: 'integer',
            title: 'Volume',
            description: 'Number of missing values in volume column'
        }
    },
    type: 'object',
    required: ['instrument', 'open', 'high', 'low', 'close', 'volume'],
    title: 'MissingDataDetail',
    description: 'Details of missing data for a specific instrument.'
} as const;

export const ModelMetricsResponseSchema = {
    properties: {
        model_type: {
            type: 'string',
            title: 'Model Type',
            description: "Model type (e.g., 'Rolling Ensemble')"
        },
        calculated_at: {
            type: 'string',
            title: 'Calculated At',
            description: 'When metrics were calculated'
        },
        frequency: {
            type: 'string',
            title: 'Frequency',
            description: "Data frequency ('day' or '1min')"
        },
        ic_metrics: {
            '$ref': '#/components/schemas/ICMetrics',
            description: 'IC analysis metrics'
        },
        long_short_metrics: {
            '$ref': '#/components/schemas/LongShortMetrics',
            description: 'Long-short strategy metrics'
        },
        quality_metrics: {
            '$ref': '#/components/schemas/QualityMetrics',
            description: 'Prediction quality metrics'
        },
        feature_importance: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/FeatureImportanceItem'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feature Importance',
            description: 'Feature importance from latest model'
        }
    },
    type: 'object',
    required: ['model_type', 'calculated_at', 'frequency', 'ic_metrics', 'long_short_metrics', 'quality_metrics'],
    title: 'ModelMetricsResponse',
    description: `Complete model metrics response.

Educational Notes:
- Contains all metrics for the active Rolling Ensemble model
- Metrics are pre-calculated during routine to avoid delays
- Used for comprehensive model performance analysis`
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PerformanceResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        initial_cash: {
            type: 'number',
            title: 'Initial Cash',
            default: 0
        },
        current_value: {
            type: 'number',
            title: 'Current Value',
            default: 0
        },
        total_return: {
            type: 'number',
            title: 'Total Return',
            default: 0
        },
        total_return_pct: {
            type: 'string',
            title: 'Total Return Pct',
            default: '0.00%'
        },
        total_trades: {
            type: 'integer',
            title: 'Total Trades',
            default: 0
        },
        buy_trades: {
            type: 'integer',
            title: 'Buy Trades',
            default: 0
        },
        sell_trades: {
            type: 'integer',
            title: 'Sell Trades',
            default: 0
        },
        trading_days: {
            type: 'integer',
            title: 'Trading Days',
            default: 0
        },
        position_count: {
            type: 'integer',
            title: 'Position Count',
            default: 0
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'PerformanceResponse',
    description: 'Response model for performance endpoint.'
} as const;

export const PlanSummarySchema = {
    properties: {
        sell_count: {
            type: 'integer',
            title: 'Sell Count'
        },
        buy_count: {
            type: 'integer',
            title: 'Buy Count'
        },
        hold_count: {
            type: 'integer',
            title: 'Hold Count'
        }
    },
    type: 'object',
    required: ['sell_count', 'buy_count', 'hold_count'],
    title: 'PlanSummary',
    description: 'Summary of trading plan.'
} as const;

export const PortfolioResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        cash: {
            type: 'number',
            title: 'Cash',
            default: 0
        },
        positions: {
            items: {
                '$ref': '#/components/schemas/PositionItem'
            },
            type: 'array',
            title: 'Positions',
            default: []
        },
        position_count: {
            type: 'integer',
            title: 'Position Count',
            default: 0
        },
        total_position_value: {
            type: 'number',
            title: 'Total Position Value',
            default: 0
        },
        total_value: {
            type: 'number',
            title: 'Total Value',
            default: 0
        },
        created_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'PortfolioResponse',
    description: 'Response model for portfolio endpoint.'
} as const;

export const PortfolioSummarySchema = {
    properties: {
        total_value: {
            type: 'number',
            title: 'Total Value'
        },
        cash: {
            type: 'number',
            title: 'Cash'
        },
        position_value: {
            type: 'number',
            title: 'Position Value'
        },
        position_count: {
            type: 'integer',
            title: 'Position Count'
        }
    },
    type: 'object',
    required: ['total_value', 'cash', 'position_value', 'position_count'],
    title: 'PortfolioSummary',
    description: 'Portfolio summary in trading plan.'
} as const;

export const PositionItemSchema = {
    properties: {
        instrument: {
            type: 'string',
            title: 'Instrument'
        },
        shares: {
            type: 'integer',
            title: 'Shares'
        },
        avg_cost: {
            type: 'number',
            title: 'Avg Cost'
        },
        current_value: {
            type: 'number',
            title: 'Current Value'
        }
    },
    type: 'object',
    required: ['instrument', 'shares', 'avg_cost', 'current_value'],
    title: 'PositionItem',
    description: 'Single position item.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QualityMetricsSchema = {
    properties: {
        long_precision: {
            type: 'number',
            title: 'Long Precision',
            description: 'Long prediction precision'
        },
        short_precision: {
            type: 'number',
            title: 'Short Precision',
            description: 'Short prediction precision'
        },
        auto_correlation: {
            type: 'number',
            title: 'Auto Correlation',
            description: 'Auto correlation (lag=1)'
        }
    },
    type: 'object',
    required: ['long_precision', 'short_precision', 'auto_correlation'],
    title: 'QualityMetrics',
    description: `Prediction quality metrics.

Educational Notes:
- Precision: Accuracy of predictions (>0.55 is good)
- Auto Correlation: Prediction stability over time (0.1-0.3 is normal)`
} as const;

export const RoutineRequestSchema = {
    properties: {
        cur_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cur Time',
            description: 'Current time in YYYY-MM-DD format. None for latest.',
            example: '2025-02-22'
        }
    },
    type: 'object',
    title: 'RoutineRequest',
    description: 'Request model for routine endpoint.'
} as const;

export const RoutineResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        cur_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cur Time'
        },
        executed_at: {
            type: 'string',
            title: 'Executed At'
        },
        steps: {
            items: {
                '$ref': '#/components/schemas/StepResult'
            },
            type: 'array',
            title: 'Steps',
            default: []
        },
        total_duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Duration Seconds'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success', 'executed_at'],
    title: 'RoutineResponse',
    description: 'Response model for routine endpoint.'
} as const;

export const SellOrderSchema = {
    properties: {
        instrument: {
            type: 'string',
            title: 'Instrument'
        },
        direction: {
            type: 'string',
            title: 'Direction',
            default: 'SELL'
        },
        sell_pct: {
            type: 'number',
            title: 'Sell Pct'
        },
        current_weight: {
            type: 'number',
            title: 'Current Weight'
        },
        reference_price: {
            type: 'number',
            title: 'Reference Price'
        },
        limit_price: {
            type: 'number',
            title: 'Limit Price'
        },
        score: {
            type: 'number',
            title: 'Score'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        instruction: {
            type: 'string',
            title: 'Instruction'
        }
    },
    type: 'object',
    required: ['instrument', 'sell_pct', 'current_weight', 'reference_price', 'limit_price', 'score', 'reason', 'instruction'],
    title: 'SellOrder',
    description: 'Sell order in trading plan.'
} as const;

export const SignalItemSchema = {
    properties: {
        datetime: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Datetime'
        },
        instrument: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instrument'
        },
        key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key'
        },
        score: {
            type: 'number',
            title: 'Score'
        }
    },
    type: 'object',
    required: ['score'],
    title: 'SignalItem',
    description: 'Single signal item.'
} as const;

export const SignalsResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        signal_count: {
            type: 'integer',
            title: 'Signal Count',
            default: 0
        },
        signals: {
            items: {
                '$ref': '#/components/schemas/SignalItem'
            },
            type: 'array',
            title: 'Signals',
            default: []
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'SignalsResponse',
    description: 'Response model for signals endpoint.'
} as const;

export const StatusResponseSchema = {
    properties: {
        is_initialized: {
            type: 'boolean',
            title: 'Is Initialized'
        },
        freq: {
            type: 'string',
            title: 'Freq'
        },
        last_routine_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Routine Time'
        },
        initialization_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Initialization Error'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config',
            default: {}
        },
        online_models_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Online Models Count'
        },
        online_models_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Online Models Error'
        }
    },
    type: 'object',
    required: ['is_initialized', 'freq'],
    title: 'StatusResponse',
    description: 'Response model for status endpoint.'
} as const;

export const StepResultSchema = {
    properties: {
        step: {
            type: 'string',
            title: 'Step'
        },
        success: {
            type: 'boolean',
            title: 'Success'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details',
            default: {}
        }
    },
    type: 'object',
    required: ['step', 'success'],
    title: 'StepResult',
    description: 'Result of a single step in the routine.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TradeItemSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        instrument: {
            type: 'string',
            title: 'Instrument'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        shares: {
            type: 'integer',
            title: 'Shares'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        value: {
            type: 'number',
            title: 'Value'
        },
        sell_pct: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sell Pct'
        },
        target_weight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Weight'
        },
        executed_at: {
            type: 'string',
            title: 'Executed At'
        }
    },
    type: 'object',
    required: ['date', 'instrument', 'action', 'shares', 'price', 'value', 'executed_at'],
    title: 'TradeItem',
    description: 'Single trade item.'
} as const;

export const TradesResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        total_trades: {
            type: 'integer',
            title: 'Total Trades',
            default: 0
        },
        trades: {
            items: {
                '$ref': '#/components/schemas/TradeItem'
            },
            type: 'array',
            title: 'Trades',
            default: []
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'TradesResponse',
    description: 'Response model for trades endpoint.'
} as const;

export const TradingPlanRequestSchema = {
    properties: {
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date',
            description: 'Date in YYYY-MM-DD format (None for latest)',
            example: '2026-02-13'
        },
        topk: {
            type: 'integer',
            maximum: 500,
            minimum: 1,
            title: 'Topk',
            description: 'Number of stocks to hold',
            default: 50
        },
        n_drop: {
            type: 'integer',
            maximum: 50,
            minimum: 0,
            title: 'N Drop',
            description: 'Number of stocks to drop each day',
            default: 5
        },
        slippage: {
            type: 'number',
            maximum: 0.1,
            minimum: 0,
            title: 'Slippage',
            description: 'Expected slippage for price estimation (default 0.1%)',
            default: 0.001
        }
    },
    type: 'object',
    title: 'TradingPlanRequest',
    description: 'Request model for trading plan endpoint.'
} as const;

export const TradingPlanResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        generated_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generated At'
        },
        strategy: {
            type: 'string',
            title: 'Strategy',
            default: 'TopkDropout'
        },
        topk: {
            type: 'integer',
            title: 'Topk',
            default: 50
        },
        n_drop: {
            type: 'integer',
            title: 'N Drop',
            default: 5
        },
        target_weight_per_stock: {
            type: 'number',
            title: 'Target Weight Per Stock',
            default: 2
        },
        slippage: {
            type: 'number',
            title: 'Slippage',
            default: 0.001
        },
        portfolio_summary: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortfolioSummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        sell_orders: {
            items: {
                '$ref': '#/components/schemas/SellOrder'
            },
            type: 'array',
            title: 'Sell Orders',
            default: []
        },
        buy_orders: {
            items: {
                '$ref': '#/components/schemas/BuyOrder'
            },
            type: 'array',
            title: 'Buy Orders',
            default: []
        },
        hold_orders: {
            items: {
                '$ref': '#/components/schemas/HoldOrder'
            },
            type: 'array',
            title: 'Hold Orders',
            default: []
        },
        summary: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlanSummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'TradingPlanResponse',
    description: 'Response model for trading plan endpoint.'
} as const;

export const TrainingStartResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        model_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Path'
        },
        test_predictions_count: {
            type: 'integer',
            title: 'Test Predictions Count',
            default: 0
        },
        experiment_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experiment Name'
        },
        timings: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timings'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'TrainingStartResponse',
    description: 'Response model for training start endpoint.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const app__api__routes__online__ResetResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['success', 'message'],
    title: 'ResetResponse',
    description: 'Response model for reset endpoint.'
} as const;

export const app__api__routes__paper_trading__ResetResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'ResetResponse',
    description: 'Response model for reset endpoint.'
} as const;