// This file is auto-generated by @hey-api/openapi-ts

export const BacktestRequestSchema = {
    properties: {
        pred_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pred Path'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        benchmark: {
            type: 'string',
            title: 'Benchmark',
            default: 'SH000300'
        },
        topk: {
            type: 'integer',
            title: 'Topk',
            default: 50
        },
        n_drop: {
            type: 'integer',
            title: 'N Drop',
            default: 5
        },
        account: {
            type: 'number',
            title: 'Account',
            default: 100000000
        }
    },
    type: 'object',
    title: 'BacktestRequest',
    description: 'Request model for backtest endpoint.'
} as const;

export const BacktestResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        trading_days: {
            type: 'integer',
            title: 'Trading Days',
            default: 0
        },
        total_return: {
            type: 'number',
            title: 'Total Return',
            default: 0
        },
        total_cost: {
            type: 'number',
            title: 'Total Cost',
            default: 0
        },
        net_return: {
            type: 'number',
            title: 'Net Return',
            default: 0
        },
        final_account: {
            type: 'number',
            title: 'Final Account',
            default: 0
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'BacktestResponse',
    description: 'Response model for backtest endpoint.'
} as const;

export const BacktestStatusResponseSchema = {
    properties: {
        ready: {
            type: 'boolean',
            title: 'Ready'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        models_count: {
            type: 'integer',
            title: 'Models Count',
            default: 0
        },
        predictions_available: {
            type: 'boolean',
            title: 'Predictions Available',
            default: false
        },
        latest_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Model'
        },
        latest_prediction_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Prediction Time'
        }
    },
    type: 'object',
    required: ['ready', 'message'],
    title: 'BacktestStatusResponse',
    description: 'Response model for backtest status check.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ClearDataResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success',
            description: 'Whether operation succeeded'
        },
        message: {
            type: 'string',
            title: 'Message',
            description: 'Result message'
        },
        cleared_size_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cleared Size Mb',
            description: 'Size of cleared data in MB'
        }
    },
    type: 'object',
    required: ['success', 'message'],
    title: 'ClearDataResponse',
    description: `Response model for data clearing operation.

Educational Notes:
- Simple response to confirm operation`
} as const;

export const ComputationStatusSchema = {
    type: 'string',
    enum: ['pending', 'computing', 'completed', 'failed'],
    title: 'ComputationStatus',
    description: 'Enumeration of factor computation status'
} as const;

export const DataSourceStatusSchema = {
    properties: {
        source_name: {
            type: 'string',
            title: 'Source Name',
            description: 'Current data source name'
        },
        data_exists: {
            type: 'boolean',
            title: 'Data Exists',
            description: 'Whether data exists in qlib_data directory'
        },
        data_range_start: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Range Start',
            description: 'Start date of available data'
        },
        data_range_end: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Range End',
            description: 'End date of available data'
        },
        instruments: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instruments',
            description: 'List of stock codes (first 10 if more than 10)'
        },
        instruments_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instruments Count',
            description: 'Number of stocks'
        },
        stock_pool: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock Pool',
            description: "Stock pool name (e.g., 'csi300', 'csi500', 'all')"
        },
        features: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Features',
            description: "List of available features (e.g., ['open', 'close', 'high', 'low', 'volume'])"
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label',
            description: "Active label name for prediction target (e.g., 'return_1d')"
        },
        data_size_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Size Mb',
            description: 'Total data size in MB'
        },
        last_updated: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Updated',
            description: 'Last update timestamp'
        }
    },
    type: 'object',
    required: ['source_name', 'data_exists'],
    title: 'DataSourceStatus',
    description: `Data source status information.

Educational Notes:
- This model represents the current state of the data
- Used to display information to users
- Not stored in database, just for API response`
} as const;

export const DataStatusResponseSchema = {
    properties: {
        exists: {
            type: 'boolean',
            title: 'Exists'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details'
        }
    },
    type: 'object',
    required: ['exists', 'message', 'details'],
    title: 'DataStatusResponse',
    description: 'Response model for data status check.'
} as const;

export const DownloadDataRequestSchema = {
    properties: {
        stock_pool: {
            type: 'string',
            title: 'Stock Pool',
            description: "Stock pool to download (e.g., 'csi300', 'csi500')",
            default: 'csi300'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date in YYYY-MM-DD format'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date in YYYY-MM-DD format'
        },
        incremental: {
            type: 'boolean',
            title: 'Incremental',
            description: 'Whether to perform incremental update (append new data only)',
            default: false
        },
        interval: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interval',
            description: "Data interval: '1d' for daily data, '1m' for minute data",
            default: '1d'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date'],
    title: 'DownloadDataRequest',
    description: `Request model for downloading data.

Educational Notes:
- This defines what parameters users need to provide
- Validation is automatic through Pydantic
- Data source is now controlled by configuration, not user input`
} as const;

export const DownloadTaskResponseSchema = {
    properties: {
        task_id: {
            type: 'string',
            title: 'Task Id',
            description: 'Unique task identifier'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: "Initial status: 'started'"
        },
        message: {
            type: 'string',
            title: 'Message',
            description: 'Human-readable message'
        }
    },
    type: 'object',
    required: ['task_id', 'status', 'message'],
    title: 'DownloadTaskResponse',
    description: `Response model for download task creation.

Educational Notes:
- Returned immediately when user starts download
- Contains task_id for tracking progress`
} as const;

export const FactorSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name',
            description: 'Factor name'
        },
        expression: {
            type: 'string',
            title: 'Expression',
            description: 'Factor expression in Qlib format'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Factor description'
        },
        factor_type: {
            '$ref': '#/components/schemas/FactorType',
            description: 'Factor type: feature (X) or label (Y)',
            default: 'feature'
        },
        status: {
            '$ref': '#/components/schemas/FactorStatus',
            description: 'Factor status',
            default: 'active'
        },
        last_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Value',
            description: 'Latest IC value'
        },
        last_ic_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Date',
            description: 'Latest IC calculation date'
        },
        avg_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Ic Value',
            description: 'Average IC value'
        },
        ic_ir_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ic Ir Ratio',
            description: 'IC Information Ratio'
        },
        last_computed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Computed At',
            description: 'Last computation time'
        },
        computation_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ComputationStatus'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Factor computation status'
        },
        data_points_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Points Count',
            description: 'Number of data points computed'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        }
    },
    type: 'object',
    required: ['name', 'expression', 'created_by'],
    title: 'Factor'
} as const;

export const FactorCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name',
            description: 'Factor name'
        },
        expression: {
            type: 'string',
            title: 'Expression',
            description: 'Factor expression in Qlib format'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Factor description'
        },
        factor_type: {
            '$ref': '#/components/schemas/FactorType',
            description: 'Factor type: feature (X) or label (Y)',
            default: 'feature'
        },
        status: {
            '$ref': '#/components/schemas/FactorStatus',
            description: 'Factor status',
            default: 'active'
        },
        last_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Value',
            description: 'Latest IC value'
        },
        last_ic_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Ic Date',
            description: 'Latest IC calculation date'
        },
        avg_ic_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Ic Value',
            description: 'Average IC value'
        },
        ic_ir_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ic Ir Ratio',
            description: 'IC Information Ratio'
        },
        last_computed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Computed At',
            description: 'Last computation time'
        },
        computation_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ComputationStatus'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Factor computation status'
        },
        data_points_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Points Count',
            description: 'Number of data points computed'
        }
    },
    type: 'object',
    required: ['name', 'expression'],
    title: 'FactorCreate'
} as const;

export const FactorStatusSchema = {
    type: 'string',
    enum: ['active', 'inactive'],
    title: 'FactorStatus',
    description: 'Enumeration of factor status'
} as const;

export const FactorTypeSchema = {
    type: 'string',
    enum: ['feature', 'label'],
    title: 'FactorType',
    description: 'Enumeration of factor types - distinguishes features from labels'
} as const;

export const FactorUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        expression: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expression'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        factor_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FactorType'
                },
                {
                    type: 'null'
                }
            ]
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FactorStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'FactorUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrainingStartResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        model_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Path'
        },
        test_predictions_count: {
            type: 'integer',
            title: 'Test Predictions Count',
            default: 0
        },
        experiment_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experiment Name'
        },
        timings: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timings'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'TrainingStartResponse',
    description: 'Response model for training start endpoint.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;