// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DataSourceGetDataSourceStatusEndpointResponse, DataSourceClearDataSourceEndpointResponse, DataSourceDownloadDataSourceEndpointData, DataSourceDownloadDataSourceEndpointResponse, FactorsCreateFactorData, FactorsCreateFactorResponse, FactorsGetFactorsData, FactorsGetFactorsResponse, FactorsGetFactorData, FactorsGetFactorResponse, FactorsUpdateFactorData, FactorsUpdateFactorResponse, FactorsDeleteFactorData, FactorsDeleteFactorResponse, FactorsValidateFactorExpressionData, FactorsValidateFactorExpressionResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, QlibWorkflowsHealthCheckResponse, QlibWorkflowsCheckDataStatusData, QlibWorkflowsCheckDataStatusResponse, QlibWorkflowsStartTrainingResponse, QlibWorkflowsGetTrainingConfigResponse, QlibWorkflowsListModelsResponse, QlibWorkflowsExecuteTrainingWorkflowData, QlibWorkflowsExecuteTrainingWorkflowResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class DataSourceService {
    /**
     * Get Data Source Status Endpoint
     * Get current data source status.
     *
     * Educational Notes:
     * - Simple API endpoint following clean architecture
     * - Delegates business logic to service layer
     * - Convert dict response to Pydantic model
     * @returns DataSourceStatus Successful Response
     * @throws ApiError
     */
    public static getDataSourceStatusEndpoint(): CancelablePromise<DataSourceGetDataSourceStatusEndpointResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/data-source/status'
        });
    }
    
    /**
     * Clear Data Source Endpoint
     * Clear all data in both qlib_data and csv_data directories.
     *
     * Educational Notes:
     * - Use DELETE method following RESTful conventions for resource deletion
     * - Clears both final data (.bin) and intermediate data (CSV) for complete reset
     * - Calls service layer for business logic separation
     * - Returns detailed information about the clearing operation
     * - Implements proper error handling with user-friendly messages
     * @returns ClearDataResponse Successful Response
     * @throws ApiError
     */
    public static clearDataSourceEndpoint(): CancelablePromise<DataSourceClearDataSourceEndpointResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/data-source/clear'
        });
    }
    
    /**
     * Download Data Source Endpoint
     * Download data from specified source using the new pipeline.
     *
     * Educational Notes:
     * - Uses the new unified pipeline: collect → normalize → dump
     * - Maintains API compatibility with existing frontend
     * - Provides better error handling and progress tracking
     * - Automatically manages workspace and cleanup
     * @param data The data for the request.
     * @param data.requestBody
     * @returns DownloadTaskResponse Successful Response
     * @throws ApiError
     */
    public static downloadDataSourceEndpoint(data: DataSourceDownloadDataSourceEndpointData): CancelablePromise<DataSourceDownloadDataSourceEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/data-source/download',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class FactorsService {
    /**
     * Create Factor
     * Create a new factor
     *
     * Educational Notes:
     * - Uses POST method for resource creation
     * - Returns 201 Created status on success
     * - Validates input data using Pydantic models
     * - Requires user authentication
     *
     * Args:
     * factor_data: Factor creation data
     * current_user: Authenticated user from JWT token
     * factor_service: Injected factor service
     *
     * Returns:
     * Created Factor instance
     *
     * Raises:
     * HTTPException: If factor creation fails
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Factor Successful Response
     * @throws ApiError
     */
    public static createFactor(data: FactorsCreateFactorData): CancelablePromise<FactorsCreateFactorResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/factors/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Factors
     * Get list of factors with optional filtering
     *
     * Educational Notes:
     * - Uses GET method for resource retrieval
     * - Supports query parameters for filtering and pagination
     * - Returns list of factors matching criteria
     * - Requires user authentication
     * - Use factor_type=feature for features (X), factor_type=label for labels (Y)
     *
     * Args:
     * status_filter: Optional status filter (ACTIVE/INACTIVE)
     * factor_type: Optional type filter (feature/label)
     * limit: Maximum number of factors to return (1-1000)
     * offset: Number of factors to skip for pagination
     * current_user: Authenticated user
     * factor_service: Injected factor service
     *
     * Returns:
     * List of Factor instances
     * @param data The data for the request.
     * @param data.statusFilter Filter by factor status
     * @param data.factorType Filter by factor type (feature or label)
     * @param data.limit Maximum number of factors to return
     * @param data.offset Number of factors to skip
     * @returns Factor Successful Response
     * @throws ApiError
     */
    public static getFactors(data: FactorsGetFactorsData = {}): CancelablePromise<FactorsGetFactorsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/factors/',
            query: {
                status_filter: data.statusFilter,
                factor_type: data.factorType,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Factor
     * Get factor by ID
     *
     * Educational Notes:
     * - Uses GET method with path parameter
     * - Returns single factor or 404 if not found
     * - Validates UUID format automatically
     *
     * Args:
     * factor_id: Factor UUID
     * current_user: Authenticated user
     * factor_service: Injected factor service
     *
     * Returns:
     * Factor instance
     *
     * Raises:
     * HTTPException: If factor not found
     * @param data The data for the request.
     * @param data.factorId
     * @returns Factor Successful Response
     * @throws ApiError
     */
    public static getFactor(data: FactorsGetFactorData): CancelablePromise<FactorsGetFactorResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/factors/{factor_id}',
            path: {
                factor_id: data.factorId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Factor
     * Update existing factor
     *
     * Educational Notes:
     * - Uses PUT method for resource update
     * - Validates expression if provided
     * - Returns updated factor or 404 if not found
     *
     * Args:
     * factor_id: Factor UUID
     * factor_data: Updated factor data
     * current_user: Authenticated user
     * factor_service: Injected factor service
     *
     * Returns:
     * Updated Factor instance
     *
     * Raises:
     * HTTPException: If factor not found or validation fails
     * @param data The data for the request.
     * @param data.factorId
     * @param data.requestBody
     * @returns Factor Successful Response
     * @throws ApiError
     */
    public static updateFactor(data: FactorsUpdateFactorData): CancelablePromise<FactorsUpdateFactorResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/factors/{factor_id}',
            path: {
                factor_id: data.factorId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Factor
     * Delete factor (soft delete)
     *
     * Educational Notes:
     * - Uses DELETE method for resource deletion
     * - Returns 204 No Content on successful deletion
     * - Performs soft delete (sets status to INACTIVE)
     *
     * Args:
     * factor_id: Factor UUID
     * current_user: Authenticated user
     * factor_service: Injected factor service
     *
     * Raises:
     * HTTPException: If factor not found or deletion fails
     * @param data The data for the request.
     * @param data.factorId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteFactor(data: FactorsDeleteFactorData): CancelablePromise<FactorsDeleteFactorResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/factors/{factor_id}',
            path: {
                factor_id: data.factorId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Validate Factor Expression
     * Validate factor expression syntax
     *
     * Educational Notes:
     * - Provides standalone expression validation
     * - Useful for frontend real-time validation
     * - Returns detailed validation results
     *
     * Args:
     * expression: Qlib expression string to validate
     * current_user: Authenticated user
     * factor_service: Injected factor service
     *
     * Returns:
     * Validation result dictionary
     * @param data The data for the request.
     * @param data.expression
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static validateFactorExpression(data: FactorsValidateFactorExpressionData): CancelablePromise<FactorsValidateFactorExpressionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/factors/validate-expression',
            query: {
                expression: data.expression
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class QlibWorkflowsService {
    /**
     * Health Check
     * Simple health check endpoint.
     *
     * Educational Notes:
     * - Returns basic status information
     * - Used to verify the API is working
     * - No complex logic, just a simple response
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<QlibWorkflowsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/qlib/health'
        });
    }
    
    /**
     * Check Data Status
     * Check if data is available for training.
     *
     * Args:
     * freq: Data frequency ("day" or "1min")
     *
     * Returns:
     * Data availability status
     * @param data The data for the request.
     * @param data.freq
     * @returns DataStatusResponse Successful Response
     * @throws ApiError
     */
    public static checkDataStatus(data: QlibWorkflowsCheckDataStatusData): CancelablePromise<QlibWorkflowsCheckDataStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/qlib/data-status/{freq}',
            path: {
                freq: data.freq
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Start Training
     * Start training workflow using configuration from file.
     *
     * This is a simplified endpoint - no configuration needed from frontend.
     * Training parameters are read from backend/app/config/training_config.yaml.
     *
     * Returns:
     * Training result with model path and metrics
     * @returns TrainingStartResponse Successful Response
     * @throws ApiError
     */
    public static startTraining(): CancelablePromise<QlibWorkflowsStartTrainingResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/qlib/training/start'
        });
    }
    
    /**
     * Get Training Config
     * Get current training configuration.
     *
     * Returns the configuration that will be used when training is started.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getTrainingConfig(): CancelablePromise<QlibWorkflowsGetTrainingConfigResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/qlib/training/config'
        });
    }
    
    /**
     * List Models
     * List all trained models.
     *
     * Returns list of model files with metadata.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static listModels(): CancelablePromise<QlibWorkflowsListModelsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/qlib/models'
        });
    }
    
    /**
     * Execute Training Workflow
     * Execute Qlib training workflow.
     *
     * Educational Notes:
     * - Uses our Pydantic models for request/response validation
     * - Calls existing QlibWorkflowService for business logic
     * - Returns structured response with training results
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TrainingWorkflowResponse Successful Response
     * @throws ApiError
     */
    public static executeTrainingWorkflow(data: QlibWorkflowsExecuteTrainingWorkflowData): CancelablePromise<QlibWorkflowsExecuteTrainingWorkflowResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/qlib/training-workflow',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}