// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response model for reset endpoint.
 */
export type app__api__routes__online__ResetResponse = {
    success: boolean;
    message: string;
};

/**
 * Response model for reset endpoint.
 */
export type app__api__routes__paper_trading__ResetResponse = {
    success: boolean;
    message?: string;
    error?: (string | null);
};

/**
 * Request model for backtest endpoint.
 */
export type BacktestRequest = {
    /**
     * Benchmark symbol for comparison (default: SH000300)
     */
    benchmark?: (string | null);
    /**
     * Number of stocks to hold (default: 50)
     */
    topk?: (number | null);
    /**
     * Number of stocks to drop each day (default: 5)
     */
    n_drop?: (number | null);
    /**
     * Initial account value (default: 100000000)
     */
    account?: (number | null);
};

/**
 * Response model for backtest endpoint.
 */
export type BacktestResponse = {
    status: string;
    start_time?: (string | null);
    end_time?: (string | null);
    freq?: (string | null);
    trading_days?: (number | null);
    signal_count?: (number | null);
    total_return?: (number | null);
    total_cost?: (number | null);
    net_return?: (number | null);
    final_account?: (number | null);
    topk?: (number | null);
    n_drop?: (number | null);
    benchmark?: (string | null);
    error?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Buy order in trading plan.
 */
export type BuyOrder = {
    instrument: string;
    direction?: string;
    target_weight: number;
    reference_price: number;
    limit_price: number;
    score: number;
    instruction: string;
    score_rank: number;
};

/**
 * Response model for data clearing operation.
 *
 * Educational Notes:
 * - Simple response to confirm operation
 */
export type ClearDataResponse = {
    /**
     * Whether operation succeeded
     */
    success: boolean;
    /**
     * Result message
     */
    message: string;
    /**
     * Size of cleared data in MB
     */
    cleared_size_mb?: (number | null);
};

/**
 * Enumeration of factor computation status
 */
export type ComputationStatus = 'pending' | 'computing' | 'completed' | 'failed';

/**
 * Details of a detected data anomaly (large step change).
 */
export type DataAnomaly = {
    /**
     * Instrument code
     */
    instrument: string;
    /**
     * Column with anomaly (e.g., 'close', 'volume')
     */
    column: string;
    /**
     * Date of anomaly occurrence
     */
    date: string;
    /**
     * Percentage change detected
     */
    pct_change: number;
};

/**
 * Comprehensive data health metrics.
 *
 * Educational Notes:
 * - Provides overview of data quality
 * - Includes both summary statistics and detailed lists
 * - Used for monitoring and alerting
 */
export type DataHealthMetrics = {
    /**
     * Whether data exists in qlib_data directory
     */
    data_exists: boolean;
    /**
     * Percentage of complete data (0-100)
     */
    completeness_percentage: number;
    /**
     * Number of instruments with missing data
     */
    missing_data_count: number;
    /**
     * Detailed list of missing data by instrument
     */
    missing_data_details: Array<MissingDataDetail>;
    /**
     * Number of detected anomalies
     */
    anomaly_count: number;
    /**
     * Detailed list of anomalies detected
     */
    anomalies: Array<DataAnomaly>;
    /**
     * Results of integrity checks
     */
    integrity_checks: IntegrityChecks;
    /**
     * Timestamp when check was performed
     */
    checked_at: string;
};

/**
 * Data source status information.
 *
 * Educational Notes:
 * - This model represents the current state of the data
 * - Used to display information to users
 * - Not stored in database, just for API response
 */
export type DataSourceStatus = {
    /**
     * Current data source name
     */
    source_name: string;
    /**
     * Whether data exists in qlib_data directory
     */
    data_exists: boolean;
    /**
     * Start date of available data
     */
    data_range_start?: (string | null);
    /**
     * End date of available data
     */
    data_range_end?: (string | null);
    /**
     * List of stock codes (first 10 if more than 10)
     */
    instruments?: (Array<(string)> | null);
    /**
     * Number of stocks
     */
    instruments_count?: (number | null);
    /**
     * Stock pool name (e.g., 'csi300', 'csi500', 'all')
     */
    stock_pool?: (string | null);
    /**
     * List of available features (e.g., ['open', 'close', 'high', 'low', 'volume'])
     */
    features?: (Array<(string)> | null);
    /**
     * Active label name for prediction target (e.g., 'return_1d')
     */
    label?: (string | null);
    /**
     * Total data size in MB
     */
    data_size_mb?: (number | null);
    /**
     * Last update timestamp
     */
    last_updated?: (string | null);
};

/**
 * Response model for data status check.
 */
export type DataStatusResponse = {
    exists: boolean;
    message: string;
    details: {
        [key: string]: unknown;
    };
};

/**
 * Request model for downloading data.
 *
 * Educational Notes:
 * - This defines what parameters users need to provide
 * - Validation is automatic through Pydantic
 * - Data source is now controlled by configuration, not user input
 */
export type DownloadDataRequest = {
    /**
     * Stock pool to download (e.g., 'csi300', 'csi500')
     */
    stock_pool?: string;
    /**
     * Start date in YYYY-MM-DD format
     */
    start_date: string;
    /**
     * End date in YYYY-MM-DD format
     */
    end_date: string;
    /**
     * Whether to perform incremental update (append new data only)
     */
    incremental?: boolean;
    /**
     * Data interval: '1d' for daily data, '1m' for minute data
     */
    interval?: (string | null);
};

/**
 * Response model for download task creation.
 *
 * Educational Notes:
 * - Returned immediately when user starts download
 * - Contains task_id for tracking progress
 */
export type DownloadTaskResponse = {
    /**
     * Unique task identifier
     */
    task_id: string;
    /**
     * Initial status: 'started'
     */
    status: string;
    /**
     * Human-readable message
     */
    message: string;
};

/**
 * Request model for execute endpoint.
 */
export type ExecuteRequest = {
    /**
     * Date in YYYY-MM-DD format (None for latest)
     */
    date?: (string | null);
    /**
     * Number of stocks to hold
     */
    topk?: number;
    /**
     * Number of stocks to drop each day
     */
    n_drop?: number;
    /**
     * Slippage for price simulation (default 0.1%)
     */
    slippage?: number;
    /**
     * If True, simulate without saving
     */
    dry_run?: boolean;
};

/**
 * Response model for execute endpoint.
 */
export type ExecuteResponse = {
    success: boolean;
    date?: (string | null);
    dry_run?: boolean;
    slippage?: number;
    sells_executed?: number;
    buys_executed?: number;
    executed_sells?: Array<TradeItem>;
    executed_buys?: Array<TradeItem>;
    final_cash?: number;
    final_position_count?: number;
    error?: (string | null);
};

export type Factor = {
    /**
     * Factor name
     */
    name: string;
    /**
     * Factor expression in Qlib format
     */
    expression: string;
    /**
     * Factor description
     */
    description?: (string | null);
    /**
     * Factor type: feature (X) or label (Y)
     */
    factor_type?: FactorType;
    /**
     * Factor status
     */
    status?: FactorStatus;
    /**
     * Latest IC value
     */
    last_ic_value?: (number | null);
    /**
     * Latest IC calculation date
     */
    last_ic_date?: (string | null);
    /**
     * Average IC value
     */
    avg_ic_value?: (number | null);
    /**
     * IC Information Ratio
     */
    ic_ir_ratio?: (number | null);
    /**
     * Last computation time
     */
    last_computed_at?: (string | null);
    /**
     * Factor computation status
     */
    computation_status?: (ComputationStatus | null);
    /**
     * Number of data points computed
     */
    data_points_count?: (number | null);
    id?: string;
    created_at?: string;
    updated_at?: string;
    created_by: string;
};

export type FactorCreate = {
    /**
     * Factor name
     */
    name: string;
    /**
     * Factor expression in Qlib format
     */
    expression: string;
    /**
     * Factor description
     */
    description?: (string | null);
    /**
     * Factor type: feature (X) or label (Y)
     */
    factor_type?: FactorType;
    /**
     * Factor status
     */
    status?: FactorStatus;
    /**
     * Latest IC value
     */
    last_ic_value?: (number | null);
    /**
     * Latest IC calculation date
     */
    last_ic_date?: (string | null);
    /**
     * Average IC value
     */
    avg_ic_value?: (number | null);
    /**
     * IC Information Ratio
     */
    ic_ir_ratio?: (number | null);
    /**
     * Last computation time
     */
    last_computed_at?: (string | null);
    /**
     * Factor computation status
     */
    computation_status?: (ComputationStatus | null);
    /**
     * Number of data points computed
     */
    data_points_count?: (number | null);
};

/**
 * Enumeration of factor status
 */
export type FactorStatus = 'active' | 'inactive';

/**
 * Enumeration of factor types - distinguishes features from labels
 */
export type FactorType = 'feature' | 'label';

export type FactorUpdate = {
    name?: (string | null);
    expression?: (string | null);
    description?: (string | null);
    factor_type?: (FactorType | null);
    status?: (FactorStatus | null);
};

/**
 * Hold order in trading plan.
 */
export type HoldOrder = {
    instrument: string;
    direction?: string;
    current_weight: number;
    target_weight: number;
    score: number;
    score_rank: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Results of data integrity checks.
 */
export type IntegrityChecks = {
    /**
     * Whether all required OHLCV columns exist
     */
    required_columns: boolean;
    /**
     * Whether factor column exists and has data
     */
    factor_column: boolean;
    /**
     * Whether all feature directories are lowercase
     */
    directory_case: boolean;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * Details of missing data for a specific instrument.
 */
export type MissingDataDetail = {
    /**
     * Instrument code
     */
    instrument: string;
    /**
     * Number of missing values in open column
     */
    open: number;
    /**
     * Number of missing values in high column
     */
    high: number;
    /**
     * Number of missing values in low column
     */
    low: number;
    /**
     * Number of missing values in close column
     */
    close: number;
    /**
     * Number of missing values in volume column
     */
    volume: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Response model for performance endpoint.
 */
export type PerformanceResponse = {
    success: boolean;
    initial_cash?: number;
    current_value?: number;
    total_return?: number;
    total_return_pct?: string;
    total_trades?: number;
    buy_trades?: number;
    sell_trades?: number;
    trading_days?: number;
    position_count?: number;
    error?: (string | null);
};

/**
 * Summary of trading plan.
 */
export type PlanSummary = {
    sell_count: number;
    buy_count: number;
    hold_count: number;
};

/**
 * Response model for portfolio endpoint.
 */
export type PortfolioResponse = {
    success: boolean;
    cash?: number;
    positions?: Array<PositionItem>;
    position_count?: number;
    total_position_value?: number;
    total_value?: number;
    created_at?: (string | null);
    updated_at?: (string | null);
    error?: (string | null);
};

/**
 * Portfolio summary in trading plan.
 */
export type PortfolioSummary = {
    total_value: number;
    cash: number;
    position_value: number;
    position_count: number;
};

/**
 * Single position item.
 */
export type PositionItem = {
    instrument: string;
    shares: number;
    avg_cost: number;
    current_value: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Request model for routine endpoint.
 */
export type RoutineRequest = {
    /**
     * Current time in YYYY-MM-DD format. None for latest.
     */
    cur_time?: (string | null);
};

/**
 * Response model for routine endpoint.
 */
export type RoutineResponse = {
    success: boolean;
    message?: (string | null);
    cur_time?: (string | null);
    executed_at: string;
    steps?: Array<StepResult>;
    total_duration_seconds?: (number | null);
    error?: (string | null);
};

/**
 * Sell order in trading plan.
 */
export type SellOrder = {
    instrument: string;
    direction?: string;
    sell_pct: number;
    current_weight: number;
    reference_price: number;
    limit_price: number;
    score: number;
    reason: string;
    instruction: string;
};

/**
 * Single signal item.
 */
export type SignalItem = {
    datetime?: (string | null);
    instrument?: (string | null);
    key?: (string | null);
    score: number;
};

/**
 * Response model for signals endpoint.
 */
export type SignalsResponse = {
    success: boolean;
    signal_count?: number;
    signals?: Array<SignalItem>;
    error?: (string | null);
};

/**
 * Response model for status endpoint.
 */
export type StatusResponse = {
    is_initialized: boolean;
    freq: string;
    last_routine_time?: (string | null);
    initialization_error?: (string | null);
    config?: {
        [key: string]: unknown;
    };
    online_models_count?: (number | null);
    online_models_error?: (string | null);
};

/**
 * Result of a single step in the routine.
 */
export type StepResult = {
    step: string;
    success: boolean;
    duration_seconds?: (number | null);
    details?: {
        [key: string]: unknown;
    };
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Single trade item.
 */
export type TradeItem = {
    date: string;
    instrument: string;
    action: string;
    shares: number;
    price: number;
    value: number;
    sell_pct?: (number | null);
    target_weight?: (number | null);
    executed_at: string;
};

/**
 * Response model for trades endpoint.
 */
export type TradesResponse = {
    success: boolean;
    total_trades?: number;
    trades?: Array<TradeItem>;
    error?: (string | null);
};

/**
 * Request model for trading plan endpoint.
 */
export type TradingPlanRequest = {
    /**
     * Date in YYYY-MM-DD format (None for latest)
     */
    date?: (string | null);
    /**
     * Number of stocks to hold
     */
    topk?: number;
    /**
     * Number of stocks to drop each day
     */
    n_drop?: number;
    /**
     * Expected slippage for price estimation (default 0.1%)
     */
    slippage?: number;
};

/**
 * Response model for trading plan endpoint.
 */
export type TradingPlanResponse = {
    success: boolean;
    date?: (string | null);
    generated_at?: (string | null);
    strategy?: string;
    topk?: number;
    n_drop?: number;
    target_weight_per_stock?: number;
    slippage?: number;
    portfolio_summary?: (PortfolioSummary | null);
    sell_orders?: Array<SellOrder>;
    buy_orders?: Array<BuyOrder>;
    hold_orders?: Array<HoldOrder>;
    summary?: (PlanSummary | null);
    error?: (string | null);
};

/**
 * Response model for training start endpoint.
 */
export type TrainingStartResponse = {
    status: string;
    message: string;
    model_path?: (string | null);
    test_predictions_count?: number;
    experiment_name?: (string | null);
    timings?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DataSourceGetDataSourceStatusEndpointResponse = (DataSourceStatus);

export type DataSourceClearDataSourceEndpointResponse = (ClearDataResponse);

export type DataSourceDownloadDataSourceEndpointData = {
    requestBody: DownloadDataRequest;
};

export type DataSourceDownloadDataSourceEndpointResponse = (DownloadTaskResponse);

export type DataSourceExportDataEndpointResponse = (unknown);

export type DataSourceGetDataHealthEndpointResponse = (DataHealthMetrics);

export type FactorsCreateFactorData = {
    requestBody: FactorCreate;
};

export type FactorsCreateFactorResponse = (Factor);

export type FactorsGetFactorsData = {
    /**
     * Filter by factor type (feature or label)
     */
    factorType?: (FactorType | null);
    /**
     * Maximum number of factors to return
     */
    limit?: number;
    /**
     * Number of factors to skip
     */
    offset?: number;
    /**
     * Filter by factor status
     */
    statusFilter?: (FactorStatus | null);
};

export type FactorsGetFactorsResponse = (Array<Factor>);

export type FactorsGetFactorData = {
    factorId: string;
};

export type FactorsGetFactorResponse = (Factor);

export type FactorsUpdateFactorData = {
    factorId: string;
    requestBody: FactorUpdate;
};

export type FactorsUpdateFactorResponse = (Factor);

export type FactorsDeleteFactorData = {
    factorId: string;
};

export type FactorsDeleteFactorResponse = (void);

export type FactorsValidateFactorExpressionData = {
    expression: string;
};

export type FactorsValidateFactorExpressionResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OnlineServingExecuteRoutineData = {
    requestBody?: RoutineRequest;
};

export type OnlineServingExecuteRoutineResponse = (RoutineResponse);

export type OnlineServingGetStatusResponse = (StatusResponse);

export type OnlineServingGetSignalsResponse = (SignalsResponse);

export type OnlineServingResetStateResponse = (app__api__routes__online__ResetResponse);

export type OnlineServingExecuteBacktestData = {
    requestBody?: (BacktestRequest | null);
};

export type OnlineServingExecuteBacktestResponse = (BacktestResponse);

export type PaperTradingGetPortfolioResponse = (PortfolioResponse);

export type PaperTradingGetTradingPlanData = {
    requestBody?: TradingPlanRequest;
};

export type PaperTradingGetTradingPlanResponse = (TradingPlanResponse);

export type PaperTradingExecuteTradesData = {
    requestBody?: ExecuteRequest;
};

export type PaperTradingExecuteTradesResponse = (ExecuteResponse);

export type PaperTradingGetTradeHistoryData = {
    instrument?: (string | null);
    limit?: number;
};

export type PaperTradingGetTradeHistoryResponse = (TradesResponse);

export type PaperTradingGetPerformanceResponse = (PerformanceResponse);

export type PaperTradingResetPaperTradingResponse = (app__api__routes__paper_trading__ResetResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TrainingCheckDataStatusData = {
    freq: string;
};

export type TrainingCheckDataStatusResponse = (DataStatusResponse);

export type TrainingStartTrainingResponse = (TrainingStartResponse);

export type TrainingGetTrainingConfigResponse = (unknown);

export type TrainingListModelsResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);