// This file is auto-generated by @hey-api/openapi-ts

/**
 * Request model for backtest endpoint.
 */
export type BacktestRequest = {
    pred_path?: (string | null);
    start_time?: (string | null);
    end_time?: (string | null);
    benchmark?: string;
    topk?: number;
    n_drop?: number;
    account?: number;
};

/**
 * Response model for backtest endpoint.
 */
export type BacktestResponse = {
    status: string;
    message: string;
    start_time?: (string | null);
    end_time?: (string | null);
    trading_days?: number;
    total_return?: number;
    total_cost?: number;
    net_return?: number;
    final_account?: number;
    error?: (string | null);
};

/**
 * Response model for backtest status check.
 */
export type BacktestStatusResponse = {
    ready: boolean;
    message: string;
    models_count?: number;
    predictions_available?: boolean;
    latest_model?: (string | null);
    latest_prediction_time?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Response model for data clearing operation.
 *
 * Educational Notes:
 * - Simple response to confirm operation
 */
export type ClearDataResponse = {
    /**
     * Whether operation succeeded
     */
    success: boolean;
    /**
     * Result message
     */
    message: string;
    /**
     * Size of cleared data in MB
     */
    cleared_size_mb?: (number | null);
};

/**
 * Enumeration of factor computation status
 */
export type ComputationStatus = 'pending' | 'computing' | 'completed' | 'failed';

/**
 * Data source status information.
 *
 * Educational Notes:
 * - This model represents the current state of the data
 * - Used to display information to users
 * - Not stored in database, just for API response
 */
export type DataSourceStatus = {
    /**
     * Current data source name
     */
    source_name: string;
    /**
     * Whether data exists in qlib_data directory
     */
    data_exists: boolean;
    /**
     * Start date of available data
     */
    data_range_start?: (string | null);
    /**
     * End date of available data
     */
    data_range_end?: (string | null);
    /**
     * List of stock codes (first 10 if more than 10)
     */
    instruments?: (Array<(string)> | null);
    /**
     * Number of stocks
     */
    instruments_count?: (number | null);
    /**
     * Stock pool name (e.g., 'csi300', 'csi500', 'all')
     */
    stock_pool?: (string | null);
    /**
     * List of available features (e.g., ['open', 'close', 'high', 'low', 'volume'])
     */
    features?: (Array<(string)> | null);
    /**
     * Active label name for prediction target (e.g., 'return_1d')
     */
    label?: (string | null);
    /**
     * Total data size in MB
     */
    data_size_mb?: (number | null);
    /**
     * Last update timestamp
     */
    last_updated?: (string | null);
};

/**
 * Response model for data status check.
 */
export type DataStatusResponse = {
    exists: boolean;
    message: string;
    details: {
        [key: string]: unknown;
    };
};

/**
 * Request model for downloading data.
 *
 * Educational Notes:
 * - This defines what parameters users need to provide
 * - Validation is automatic through Pydantic
 * - Data source is now controlled by configuration, not user input
 */
export type DownloadDataRequest = {
    /**
     * Stock pool to download (e.g., 'csi300', 'csi500')
     */
    stock_pool?: string;
    /**
     * Start date in YYYY-MM-DD format
     */
    start_date: string;
    /**
     * End date in YYYY-MM-DD format
     */
    end_date: string;
    /**
     * Whether to perform incremental update (append new data only)
     */
    incremental?: boolean;
    /**
     * Data interval: '1d' for daily data, '1m' for minute data
     */
    interval?: (string | null);
};

/**
 * Response model for download task creation.
 *
 * Educational Notes:
 * - Returned immediately when user starts download
 * - Contains task_id for tracking progress
 */
export type DownloadTaskResponse = {
    /**
     * Unique task identifier
     */
    task_id: string;
    /**
     * Initial status: 'started'
     */
    status: string;
    /**
     * Human-readable message
     */
    message: string;
};

export type Factor = {
    /**
     * Factor name
     */
    name: string;
    /**
     * Factor expression in Qlib format
     */
    expression: string;
    /**
     * Factor description
     */
    description?: (string | null);
    /**
     * Factor type: feature (X) or label (Y)
     */
    factor_type?: FactorType;
    /**
     * Factor status
     */
    status?: FactorStatus;
    /**
     * Latest IC value
     */
    last_ic_value?: (number | null);
    /**
     * Latest IC calculation date
     */
    last_ic_date?: (string | null);
    /**
     * Average IC value
     */
    avg_ic_value?: (number | null);
    /**
     * IC Information Ratio
     */
    ic_ir_ratio?: (number | null);
    /**
     * Last computation time
     */
    last_computed_at?: (string | null);
    /**
     * Factor computation status
     */
    computation_status?: (ComputationStatus | null);
    /**
     * Number of data points computed
     */
    data_points_count?: (number | null);
    id?: string;
    created_at?: string;
    updated_at?: string;
    created_by: string;
};

export type FactorCreate = {
    /**
     * Factor name
     */
    name: string;
    /**
     * Factor expression in Qlib format
     */
    expression: string;
    /**
     * Factor description
     */
    description?: (string | null);
    /**
     * Factor type: feature (X) or label (Y)
     */
    factor_type?: FactorType;
    /**
     * Factor status
     */
    status?: FactorStatus;
    /**
     * Latest IC value
     */
    last_ic_value?: (number | null);
    /**
     * Latest IC calculation date
     */
    last_ic_date?: (string | null);
    /**
     * Average IC value
     */
    avg_ic_value?: (number | null);
    /**
     * IC Information Ratio
     */
    ic_ir_ratio?: (number | null);
    /**
     * Last computation time
     */
    last_computed_at?: (string | null);
    /**
     * Factor computation status
     */
    computation_status?: (ComputationStatus | null);
    /**
     * Number of data points computed
     */
    data_points_count?: (number | null);
};

/**
 * Enumeration of factor status
 */
export type FactorStatus = 'active' | 'inactive';

/**
 * Enumeration of factor types - distinguishes features from labels
 */
export type FactorType = 'feature' | 'label';

export type FactorUpdate = {
    name?: (string | null);
    expression?: (string | null);
    description?: (string | null);
    factor_type?: (FactorType | null);
    status?: (FactorStatus | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Response model for training start endpoint.
 */
export type TrainingStartResponse = {
    status: string;
    message: string;
    model_path?: (string | null);
    test_predictions_count?: number;
    experiment_name?: (string | null);
    timings?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type BacktestGetBacktestConfigResponse = (unknown);

export type BacktestGetBacktestStatusResponse = (BacktestStatusResponse);

export type BacktestExecuteBacktestData = {
    requestBody?: (BacktestRequest | null);
};

export type BacktestExecuteBacktestResponse = (BacktestResponse);

export type DataSourceGetDataSourceStatusEndpointResponse = (DataSourceStatus);

export type DataSourceClearDataSourceEndpointResponse = (ClearDataResponse);

export type DataSourceDownloadDataSourceEndpointData = {
    requestBody: DownloadDataRequest;
};

export type DataSourceDownloadDataSourceEndpointResponse = (DownloadTaskResponse);

export type DataSourceExportDataEndpointResponse = (unknown);

export type FactorsCreateFactorData = {
    requestBody: FactorCreate;
};

export type FactorsCreateFactorResponse = (Factor);

export type FactorsGetFactorsData = {
    /**
     * Filter by factor type (feature or label)
     */
    factorType?: (FactorType | null);
    /**
     * Maximum number of factors to return
     */
    limit?: number;
    /**
     * Number of factors to skip
     */
    offset?: number;
    /**
     * Filter by factor status
     */
    statusFilter?: (FactorStatus | null);
};

export type FactorsGetFactorsResponse = (Array<Factor>);

export type FactorsGetFactorData = {
    factorId: string;
};

export type FactorsGetFactorResponse = (Factor);

export type FactorsUpdateFactorData = {
    factorId: string;
    requestBody: FactorUpdate;
};

export type FactorsUpdateFactorResponse = (Factor);

export type FactorsDeleteFactorData = {
    factorId: string;
};

export type FactorsDeleteFactorResponse = (void);

export type FactorsValidateFactorExpressionData = {
    expression: string;
};

export type FactorsValidateFactorExpressionResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TrainingCheckDataStatusData = {
    freq: string;
};

export type TrainingCheckDataStatusResponse = (DataStatusResponse);

export type TrainingStartTrainingResponse = (TrainingStartResponse);

export type TrainingGetTrainingConfigResponse = (unknown);

export type TrainingListModelsResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);