#!/usr/bin/env python3
"""
Test script for sending ETF Enhanced Indexing signal email.

This script reads the latest portfolio JSON file generated by routine
and sends an email using the actual code path (same as routine does).

Usage:
    docker compose exec backend python /app/temp_scripts/test_email_signal.py
"""

import sys
import os
import json
import glob

# Add the app directory to the path
sys.path.insert(0, "/app")


def find_latest_portfolio_json():
    """Find the latest portfolio JSON file from ETF Enhanced Indexing output."""
    output_dir = "/app/output/etf_enhanced_indexing"

    if not os.path.exists(output_dir):
        print(f"❌ Output directory not found: {output_dir}")
        return None

    # Find all JSON files
    json_files = glob.glob(os.path.join(output_dir, "target_portfolio_*.json"))

    if not json_files:
        print(f"❌ No portfolio JSON files found in {output_dir}")
        return None

    # Sort by modification time, get the latest
    latest_file = max(json_files, key=os.path.getmtime)
    return latest_file


def load_portfolio_data(json_path):
    """Load portfolio data from JSON file."""
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def main():
    print()
    print("╔════════════════════════════════════════════════════════════╗")
    print("║     QuantBot ETF Enhanced Indexing Email Test Script      ║")
    print("╚════════════════════════════════════════════════════════════╝")
    print()

    # Step 1: Find and load the latest portfolio JSON
    print("=" * 60)
    print("Step 1: Loading Latest Portfolio Data")
    print("=" * 60)

    json_path = find_latest_portfolio_json()
    if not json_path:
        print("Please run routine first to generate portfolio data.")
        return

    print(f"📄 Found latest portfolio file: {json_path}")

    portfolio_data = load_portfolio_data(json_path)

    # Print summary
    print()
    print("Portfolio Data Summary:")
    print(f"  - Generated At: {portfolio_data.get('generated_at', 'N/A')}")
    print(f"  - Trade Date: {portfolio_data.get('trade_date', 'N/A')}")
    print(f"  - Signal Date: {portfolio_data.get('signal_for_date', 'N/A')}")
    print(f"  - Total Value: ¥{portfolio_data.get('total_value', 0):,}")

    weights = portfolio_data.get("weights", {})
    print(f"  - ETF Weight: {weights.get('etf_weight', 0):.0%}")
    print(f"  - Alpha Weight: {weights.get('alpha_weight', 0):.0%}")
    print(f"  - Score Spread: {weights.get('score_spread', 0):.4f}")

    summary = portfolio_data.get("summary", {})
    print(f"  - Total Positions: {summary.get('total_positions', 0)}")
    print(
        f"  - Buy: {summary.get('buy_count', 0)}, Sell: {summary.get('sell_count', 0)}, Hold: {summary.get('hold_count', 0)}"
    )
    print()

    # Step 2: Send email using the actual code path
    print("=" * 60)
    print("Step 2: Sending Email (Using Actual Code Path)")
    print("=" * 60)

    # This is the same code path used in online_serving_service._send_etf_portfolio_email
    from app.services.notification_service import get_notification_service
    from app.core.config import settings

    print(f"Email enabled: {settings.emails_enabled}")
    print(f"SMTP Host: {settings.SMTP_HOST}")
    print()

    if not settings.emails_enabled:
        print("❌ Email is not configured. Please set SMTP settings in .env file.")
        return

    notification_service = get_notification_service()

    print("Calling notification_service.send_etf_enhanced_portfolio_email()...")
    print()

    # Call the actual send method (same as routine does)
    result = notification_service.send_etf_enhanced_portfolio_email(portfolio_data)

    if result.get("success"):
        print(f"✅ Email sent successfully!")
        print(f"   Message: {result.get('message')}")
    else:
        print(f"❌ Failed to send email")
        print(f"   Error: {result.get('error')}")
        if result.get("errors"):
            print(f"   Details: {result.get('errors')}")

    print()
    print("=" * 60)
    print("Done!")
    print("=" * 60)


if __name__ == "__main__":
    main()
