#!/usr/bin/env python3
"""
Test script for Signal Export Service

This script tests the signal export functionality using real portfolio data
generated by the routine execution.
"""

import sys
import json
from pathlib import Path

# Add the app directory to Python path
sys.path.append("/app")

from app.services.signal_export_service import get_signal_export_service
from app.services.enhanced_indexing_service import get_enhanced_indexing_service


def test_signal_export():
    """Test signal export with real portfolio data."""
    print("=" * 60)
    print("Testing Signal Export Service")
    print("=" * 60)

    # Step 1: Load real portfolio data
    print("\n1. Loading portfolio data...")
    enhanced_service = get_enhanced_indexing_service()
    portfolio_data = enhanced_service.load_portfolio("2026-03-13")

    if not portfolio_data:
        print("❌ Failed to load portfolio data")
        return False

    target_portfolio = portfolio_data.get("portfolio", [])
    print(f"✅ Loaded portfolio with {len(target_portfolio)} items")

    if target_portfolio:
        print(
            f"   First 5 stocks: {[item['instrument'] for item in target_portfolio[:5]]}"
        )
        print(
            f"   Top stock: {target_portfolio[0]['instrument']} (score: {target_portfolio[0].get('score', 'N/A')})"
        )

    # Step 2: Initialize signal export service
    print("\n2. Initializing signal export service...")
    signal_service = get_signal_export_service(
        etf_weight=0.7, alpha_weight=0.3, max_stocks=10
    )
    print(f"✅ Service initialized:")
    print(f"   ETF weight: {signal_service.etf_weight}")
    print(f"   Alpha weight: {signal_service.alpha_weight}")
    print(f"   Max stocks: {signal_service.max_stocks}")
    print(f"   Output dir: {signal_service.output_dir}")

    # Step 3: Export signals
    print("\n3. Exporting signals...")
    try:
        output_file = signal_service.export_signals(
            portfolio_data, trade_date="2026-03-15"
        )
        print(f"✅ Signal exported to: {output_file}")
    except Exception as e:
        print(f"❌ Export failed: {e}")
        return False

    # Step 4: Validate signal file
    print("\n4. Validating signal file...")
    try:
        with open(output_file, "r", encoding="utf-8") as f:
            signal_data = json.load(f)

        # Check structure
        required_keys = [
            "generated_at",
            "trade_date",
            "index",
            "strategy",
            "positions",
            "summary",
        ]
        missing_keys = [key for key in required_keys if key not in signal_data]

        if missing_keys:
            print(f"❌ Missing keys in signal file: {missing_keys}")
            return False

        print("✅ Signal file structure is valid")

        # Display summary
        summary = signal_data["summary"]
        positions = signal_data["positions"]

        print(f"\n📊 Signal Summary:")
        print(f"   Trade date: {signal_data['trade_date']}")
        print(f"   Index: {signal_data['index']}")
        print(f"   Total positions: {summary['total_positions']}")
        print(f"   ETF positions: {summary['etf_positions']}")
        print(f"   Stock positions: {summary['stock_positions']}")
        print(f"   Total weight: {summary['total_weight']:.4f}")

        # Validate weights
        total_weight = sum(pos["weight"] for pos in positions)
        weight_diff = abs(total_weight - 1.0)

        if weight_diff > 0.01:
            print(
                f"⚠️  Weight validation warning: total={total_weight:.4f}, diff={weight_diff:.4f}"
            )
        else:
            print(f"✅ Weight validation passed: total={total_weight:.4f}")

        # Display positions
        print(f"\n📈 Positions:")
        for i, pos in enumerate(positions):
            pos_type = pos["type"].upper()
            weight_pct = pos["weight"] * 100
            if pos["type"] == "etf":
                print(f"   {i+1}. {pos['symbol']} ({pos_type}) - {weight_pct:.2f}%")
            else:
                score = pos.get("score", 0)
                rank = pos.get("rank", 0)
                print(
                    f"   {i+1}. {pos['symbol']} ({pos_type}) - {weight_pct:.2f}% (score: {score:.3f}, rank: {rank})"
                )

        return True

    except Exception as e:
        print(f"❌ Validation failed: {e}")
        return False


def test_etf_only_signal():
    """Test ETF-only signal generation."""
    print("\n" + "=" * 60)
    print("Testing ETF-Only Signal Generation")
    print("=" * 60)

    signal_service = get_signal_export_service()

    # Test with empty portfolio
    empty_portfolio = {
        "target_portfolio": [],
        "summary": {"note": "Empty portfolio for testing"},
    }

    try:
        output_file = signal_service.export_signals(
            empty_portfolio, trade_date="2026-03-15-etf-only"
        )
        print(f"✅ ETF-only signal exported to: {output_file}")

        # Validate
        with open(output_file, "r", encoding="utf-8") as f:
            signal_data = json.load(f)

        positions = signal_data["positions"]
        if (
            len(positions) == 1
            and positions[0]["type"] == "etf"
            and positions[0]["weight"] == 1.0
        ):
            print("✅ ETF-only signal validation passed")
            return True
        else:
            print("❌ ETF-only signal validation failed")
            return False

    except Exception as e:
        print(f"❌ ETF-only test failed: {e}")
        return False


if __name__ == "__main__":
    print("Starting Signal Export Service Tests...")

    success1 = test_signal_export()
    success2 = test_etf_only_signal()

    print("\n" + "=" * 60)
    print("Test Results Summary")
    print("=" * 60)
    print(f"Signal Export Test: {'✅ PASSED' if success1 else '❌ FAILED'}")
    print(f"ETF-Only Test: {'✅ PASSED' if success2 else '❌ FAILED'}")

    if success1 and success2:
        print("\n🎉 All tests passed!")
        sys.exit(0)
    else:
        print("\n💥 Some tests failed!")
        sys.exit(1)
