"""replace manual time fields with auto split in modeltraining

Revision ID: 081744a8e420
Revises: 13d93f395e96
Create Date: 2026-01-26 06:13:58.506003

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '081744a8e420'
down_revision = '13d93f395e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modeltraining', sa.Column('data_start_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('modeltraining', sa.Column('data_end_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('modeltraining', sa.Column('train_ratio', sa.Float(), nullable=False))
    op.add_column('modeltraining', sa.Column('valid_ratio', sa.Float(), nullable=False))
    op.drop_column('modeltraining', 'train_start_time')
    op.drop_column('modeltraining', 'valid_end_time')
    op.drop_column('modeltraining', 'valid_start_time')
    op.drop_column('modeltraining', 'train_end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modeltraining', sa.Column('train_end_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('modeltraining', sa.Column('valid_start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('modeltraining', sa.Column('valid_end_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('modeltraining', sa.Column('train_start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('modeltraining', 'valid_ratio')
    op.drop_column('modeltraining', 'train_ratio')
    op.drop_column('modeltraining', 'data_end_time')
    op.drop_column('modeltraining', 'data_start_time')
    # ### end Alembic commands ###
