"""rename factor_ids to factor_handler in modeltraining

Revision ID: 13d93f395e96
Revises: 77f04ed09ace
Create Date: 2026-01-26 05:56:00.005678

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "13d93f395e96"
down_revision = "77f04ed09ace"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column to preserve existing data
    op.alter_column("modeltraining", "factor_ids", new_column_name="factor_handler")

    # Update default value for existing rows (convert "[]" to "alpha158")
    op.execute(
        "UPDATE modeltraining SET factor_handler = 'alpha158' WHERE factor_handler = '[]'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column back to original name
    op.alter_column("modeltraining", "factor_handler", new_column_name="factor_ids")

    # Restore default value for existing rows (convert "alpha158" back to "[]")
    op.execute(
        "UPDATE modeltraining SET factor_ids = '[]' WHERE factor_ids = 'alpha158'"
    )
    # ### end Alembic commands ###
