"""Add IC analysis and computation fields to Factor model

Revision ID: 1e5153956860
Revises: 081744a8e420
Create Date: 2026-02-18 04:31:16.428390

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e5153956860'
down_revision = '081744a8e420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factoranalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('factor_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('ic_value', sa.Float(), nullable=True),
    sa.Column('ic_pvalue', sa.Float(), nullable=True),
    sa.Column('rank_ic_value', sa.Float(), nullable=True),
    sa.Column('rank_ic_pvalue', sa.Float(), nullable=True),
    sa.Column('correlation_matrix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('std_value', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('analysis_period_start', sa.DateTime(), nullable=True),
    sa.Column('analysis_period_end', sa.DateTime(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['factor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factordependency',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('factor_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['factor_id'], ['factor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('factor', sa.Column('last_ic_value', sa.Float(), nullable=True))
    op.add_column('factor', sa.Column('last_ic_date', sa.DateTime(), nullable=True))
    op.add_column('factor', sa.Column('avg_ic_value', sa.Float(), nullable=True))
    op.add_column('factor', sa.Column('ic_ir_ratio', sa.Float(), nullable=True))
    op.add_column('factor', sa.Column('last_computed_at', sa.DateTime(), nullable=True))
    op.add_column('factor', sa.Column('computation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('factor', sa.Column('data_points_count', sa.Integer(), nullable=True))
    op.drop_column('factor', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factor', sa.Column('category', postgresql.ENUM('TECHNICAL', 'PRICE_VOLUME', 'FUNDAMENTAL', 'CUSTOM', name='factorcategory'), autoincrement=False, nullable=False))
    op.drop_column('factor', 'data_points_count')
    op.drop_column('factor', 'computation_status')
    op.drop_column('factor', 'last_computed_at')
    op.drop_column('factor', 'ic_ir_ratio')
    op.drop_column('factor', 'avg_ic_value')
    op.drop_column('factor', 'last_ic_date')
    op.drop_column('factor', 'last_ic_value')
    op.drop_table('factordependency')
    op.drop_table('factoranalysis')
    # ### end Alembic commands ###
