"""Add Factor model for quantitative factor management

Revision ID: 537539eac088
Revises: a8b96081a83a
Create Date: 2026-01-14 08:57:55.704473

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '537539eac088'
down_revision = 'a8b96081a83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('category', sa.Enum('TECHNICAL', 'PRICE_VOLUME', 'FUNDAMENTAL', 'CUSTOM', name='factorcategory'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='factorstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factor')
    # ### end Alembic commands ###
