"""Remove model_file_path and status from mlmodel table

Revision ID: 65cd8caa3dae
Revises: 9be3fbdf7e67
Create Date: 2026-01-15 11:02:41.857543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65cd8caa3dae'
down_revision = '9be3fbdf7e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mlmodel', 'model_file_path')
    op.drop_column('mlmodel', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlmodel', sa.Column('status', postgresql.ENUM('TRAINED', 'OUTDATED', 'UNTRAINED', name='modelstatus'), autoincrement=False, nullable=False))
    op.add_column('mlmodel', sa.Column('model_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
