"""Add ModelTraining and Backtest tables

Revision ID: 77f04ed09ace
Revises: 65cd8caa3dae
Create Date: 2026-01-16 03:00:17.400941

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77f04ed09ace'
down_revision = '65cd8caa3dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modeltraining',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('factor_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('train_start_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('train_end_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('valid_start_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('valid_end_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('training_config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_gpu', sa.Boolean(), nullable=False),
    sa.Column('num_workers', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='trainingstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('model_file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('training_metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['mlmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model_training_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('backtest_start_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('backtest_end_time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('benchmark', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('account', sa.Float(), nullable=False),
    sa.Column('exchange_config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('report_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('positions_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('performance_metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['model_training_id'], ['modeltraining.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest')
    op.drop_table('modeltraining')
    # ### end Alembic commands ###
